import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import {usePokemon} from '../context/store';
export {getServerSideProps} from '../context/store';

export default function Home() {
  const {pokemon, filter, setFilter} = usePokemon();
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.search}>
        <input
          type="text"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className={styles.search}
        />
      </div>
      <div className={styles.container}>
        {pokemon.slice(0, 12).map((p) => (
          <div key={p.id} className={styles.card}>
            <img
              alt={p.name}
              src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`}
            />
            <h3>{p.name}</h3>
          </div>
        ))}
      </div>
    </div>
  );
}
